version: "3"

services:
    postgres:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=12345
        volumes:
            - ./postgres_data/:/var/lib/postgresql/data/
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4:4.15
        volumes:
            - ./pgadmin_data:/var/lib/pgadmin
        ports:
            - "9090:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin
            - PGADMIN_DEFAULT_PASSWORD=1234
        logging:
            driver: none
                